export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";

export const USER_PROFILE_REQUESTED = "USER_PROFILE_REQUESTED";
export const USER_PROFILE_SUCCEEDED = "USER_PROFILE_SUCCEEDED";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const SET_SIDE_NAV_OPEN = "SET_SIDE_NAV_OPEN"
