export enum NavType {
  ITEM,
  MENU,
  SUBMENU,
}

export const sideNavMenu = [
  {
    type: NavType.MENU,
    key: "dashboard",
    icon: "",
    title: "Dashboard",
    defaultOpened: true,
    items: [
      {
        type: NavType.ITEM,
        key: "summary",
        icon: "",
        title: "Summary",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "procurement-item",
        icon: "",
        title: "Procurement",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "performance-item",
        icon: "",
        title: "Performance",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "forecasting-item",
        icon: "",
        title: "Forecasting",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "compliance-item",
        icon: "",
        title: "Compliance",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "operations-item",
        icon: "",
        title: "Operations",
        path: "/",
        isSubMenu: false,
      },
    ],
  },
  // procurement
  {
    type: NavType.MENU,
    key: "procurement",
    icon: "",
    title: "Procurement",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "procurement/rfps",
        icon: "",
        title: "RFP",
        path: "/procurement/rfps",
      },
      {
        type: NavType.ITEM,
        key: "procurement/inventory",
        icon: "",
        title: "Inventory",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "procurement/nfa",
        icon: "",
        title: "NFA",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "procurement/work-order",
        icon: "",
        title: "Work Order",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "procurement/ian",
        icon: "",
        title: "Create IAN",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "procurement/pn",
        icon: "",
        title: "Payment Note",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "procurement/vendors",
        icon: "",
        title: "Vendor Master",
        path: "/procurement/vendors",
      },
    ],
  },
  // performance
  {
    type: NavType.MENU,
    key: "performance",
    icon: "",
    title: "Performance",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "performance/plant-wise",
        icon: "",
        title: "Plant Wise",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "performance/breakdown-level",
        icon: "",
        title: "Breakdown Level",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "performance/equipment-level",
        icon: "",
        title: "Equipment Level",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "performance/weather-analysis",
        icon: "",
        title: "Weather Analysis",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "performance/prediction",
        icon: "",
        title: "Prediction",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "performance/testing-reports",
        icon: "",
        title: "Testing reports",
        path: "/",
      },
    ],
  },
  // f-s
  {
    type: NavType.MENU,
    key: "fs",
    icon: "",
    title: "Forecasting",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "fs/commercial",
        icon: "",
        title: "Commercial",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "fs/dsm-analysis",
        icon: "",
        title: "DSM Analysis",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "fs/qca-performance",
        icon: "",
        title: "QCA Performance",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "fs/availabilty-analysis",
        icon: "",
        title: "Availabilty Analysis",
        path: "/",
      },
    ],
  },
  // f-a
  {
    type: NavType.MENU,
    key: "fa",
    icon: "",
    title: "Finance",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "fs/payment-tracking",
        icon: "",
        title: "Payment Tracking",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "fs/payment-calendar",
        icon: "",
        title: "Payment Calendar",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "fs/accounting-config",
        icon: "",
        title: "Accounting Config",
        path: "/",
      },
    ],
  },
  // compliance
  {
    type: NavType.MENU,
    key: "compliance",
    icon: "",
    title: "Compliance",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "compliance/compliance-report",
        icon: "",
        title: "Compliance Report",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "compliance/all-covenants",
        icon: "",
        title: "All Covenants",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "compliance/calendar",
        icon: "",
        title: "Calendar",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "compliance/add-contract",
        icon: "",
        title: "Add Contract",
        path: "/",
      },
    ],
  },
  // operations
  {
    type: NavType.MENU,
    key: "operations",
    icon: "",
    title: "Operations",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "operations/calendar",
        icon: "",
        title: "Calendar",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "operations/PPM",
        icon: "",
        title: "PPM",
        path: "operations/ppms",
      },
      {
        type: NavType.ITEM,
        key: "operations/breakdown",
        icon: "",
        title: "Breakdown",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "operations/hse",
        icon: "",
        title: "HSE",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "operations/incident-reports",
        icon: "",
        title: "Incident Reports",
        path: "/",
      },
      {
        type: NavType.ITEM,
        key: "operations/jobs",
        icon: "",
        title: "Jobs",
        path: "/",
      },
    ],
  },
  // alarms-events
  {
    type: NavType.MENU,
    key: "alarms-events",
    icon: "",
    title: "Alarms & Events",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "all-alarms",
        icon: "",
        title: "All Alarms",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "all-events",
        icon: "",
        title: "All Events",
        path: "/",
        isSubMenu: false,
      },
    ],
  },
  // settings
  {
    type: NavType.MENU,
    key: "settings",
    icon: "",
    title: "Settings",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "plant-configuration",
        icon: "",
        title: "Plant Configuration",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "client-configuration",
        icon: "",
        title: "Client Configuration",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "user-management",
        icon: "",
        title: "User Management",
        path: "/",
        isSubMenu: false,
      },
    ],
  },
  // help-support
  {
    type: NavType.MENU,
    key: "help-support",
    icon: "",
    title: "Help & Support",
    defaultOpened: false,
    items: [
      {
        type: NavType.ITEM,
        key: "all-ticket",
        icon: "",
        title: "All Ticket",
        path: "/",
        isSubMenu: false,
      },
      {
        type: NavType.ITEM,
        key: "raise-ticket",
        icon: "",
        title: "Raise Ticket",
        path: "/",
        isSubMenu: false,
      },
    ],
  },
];
